# Generated by Django 4.2.5 on 2023-09-11 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Произведен')),
                ('how_much', models.CharField(max_length=99999, verbose_name='Сумма')),
                ('who_get', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_get', to='users.user', verbose_name='Получатель')),
                ('who_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Who_transfer', to='users.user', verbose_name='Кто отправил')),
            ],
            options={
                'verbose_name': 'Истории',
                'verbose_name_plural': 'История',
            },
        ),
    ]
