# Generated by Django 4.2.5 on 2023-09-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('number', models.CharField(max_length=15, verbose_name='Телефоный номер')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('money', models.CharField(blank=True, default=0, max_length=999999, null=True, verbose_name='Баланс')),
                ('id_card', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Номер счета')),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователь',
            },
        ),
    ]
